name: Build and Deploy to GKE

on:
  push:
    branches: [ "develop" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west1
  GKE_CLUSTER: raito-cluster   
  GKE_ZONE: europe-west1 
  DEPLOYMENT_NAME: raito-app-:$(date +%s)
  REPOSITORY: raito-docker-repo
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Setup
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        export_default_credentials: true

    - name: Configure Docker Client
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      
    - name: Build 
      run: 
        docker build -f front.dockerfile . --tag front-container:1 &&
        docker build -f backend.dockerfile . --tag backend-container:1 
        
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: 
        docker tag backend-container:1 europe-west1-docker.pkg.dev/raito-369114/raito-docker-repo/backend-container &&
        docker tag front-container:1 europe-west1-docker.pkg.dev/raito-369114/raito-docker-repo/front-container &&
        docker push europe-west1-docker.pkg.dev/raito-369114/raito-docker-repo/backend-container &&
        docker push europe-west1-docker.pkg.dev/raito-369114/raito-docker-repo/front-container
        
